# setup some basic app parameters
app:
  # development, test, production
  environment:          development
  # @see list of supported timezones <http://www.php.net/manual/en/timezones.php>
  timezone:             America/New_York
  charset:              UTF-8

# setup database connections
db:
  connection:           "mysql://root:password@localhost/app-db"
